// ============================================
// NOTE ANALYSIS TYPES
// ============================================

export type Vector = number[];

export interface CurrentNote {
  title: string;
  tags: string[];
  frontmatter: Record<string, any>;
  content: string;
  contentPreview: string;      // First 500 chars
  headings: string[];
  links: string[];
  embeddings?: Vector;
}

export interface ExtractedNoteData {
  title: string;
  tags: string[];
  keyTopics: string[];          // LLM-extracted
  contentType: 'essay' | 'research' | 'project' | 'resource' | 'personal';
  semanticSignature: {
    primaryTheme: string;
    secondaryThemes: string[];
    keywords: string[];
  };
}

// ============================================
// VAULT STRUCTURE TYPES
// ============================================

export interface FolderStructure {
  path: string;
  name: string;
  depth: number;
  children: FolderStructure[];
  files: VaultFile[];
  folderNote?: FolderNoteContent;
}

export interface VaultFile {
  path: string;
  name: string;
  created: number;
  modified: number;
  size: number;
}

export interface FolderNoteContent {
  path: string;
  title: string;
  description: string;
  keyTopics: string[];
  relatedFolders: string[];
  isAutoGenerated: boolean;
}

export interface FolderProfile {
  folderPath: string;
  folderName: string;
  fileCount: number;
  avgNoteAge: number;          // in days
  themeKeywords: string[];
  description: string;
  folderNote: FolderNoteContent | null;
  embeddings?: Vector;
  coherenceScore: number;      // 0-1, how similar notes are within folder
  examples: string[];          // Sample note titles
}

// ============================================
// RECOMMENDATION TYPES
// ============================================

export interface FolderRecommendation {
  folderPath: string;
  folderName: string;
  confidence: number;           // 0-100%
  reasoning: string;
  matchedTopics: string[];
  matchStrength: 'strong' | 'moderate' | 'weak';
}

export interface RecommendationResult {
  primaryRecommendation: FolderRecommendation;
  alternatives: FolderRecommendation[];
  shouldCreateNewFolder: boolean;
  suggestedNewFolder?: {
    name: string;
    reasoning: string;
    suggestedParent?: string;
  };
  analysisMetadata: {
    timestamp: number;
    processingTime: number;       // ms
    modelsUsed: string[];
    tokensUsed?: number;
  };
}

// ============================================
// VAULT ANALYSIS TYPES
// ============================================

export interface VaultAnalysisReport {
  vaultStats: {
    totalNotes: number;
    totalFolders: number;
    avgNotesPerFolder: number;
    largestFolder: { path: string; count: number };
    smallestFolder: { path: string; count: number };
  };
  issues: VaultIssue[];
  recommendations: ReclassificationAction[];
  optimizationScore: {
    current: number;             // 0-100
    potential: number;           // 0-100
    improvement: number;         // potential - current
  };
}

export interface VaultIssue {
  type: 'orphaned' | 'overcrowded' | 'semantic_overlap' | 'empty' | 'ambiguous';
  severity: 'high' | 'medium' | 'low';
  description: string;
  affectedFolders?: string[];
  affectedNotes?: string[];
  suggestedAction: string;
}

export interface ReclassificationAction {
  type: 'move' | 'create' | 'merge' | 'rename' | 'split';
  source?: string;
  target: string;
  notes?: string[];
  reasoning: string;
  confidenceScore: number;
}

// ============================================
// OPENAI API TYPES
// ============================================

export interface ChatMessage {
  role: 'system' | 'user' | 'assistant';
  content: string;
}

export interface OpenAIRequest {
  model: string;
  messages: ChatMessage[];
  temperature: number;
  max_tokens: number;
  top_p?: number;
  frequency_penalty?: number;
  presence_penalty?: number;
}

export interface OpenAIResponse {
  id: string;
  object: string;
  created: number;
  model: string;
  choices: Array<{
    index: number;
    message: ChatMessage;
    finish_reason: string;
  }>;
  usage: {
    prompt_tokens: number;
    completion_tokens: number;
    total_tokens: number;
  };
}

// ============================================
// SMART CONNECTIONS TYPES
// ============================================

export interface SmartConnectionsData {
  isAvailable: boolean;
  vectorDBPath: string;
  embeddingModel: 'local' | 'openai' | 'other';
  totalEmbeddings: number;
}

export interface SimilarityMatch {
  notePath: string;
  noteTitle: string;
  similarityScore: number;  // 0-1
}

// ============================================
// CACHE TYPES
// ============================================

export interface CacheEntry<T> {
  data: T;
  timestamp: number;
  ttl: number;              // milliseconds
}

export interface EmbeddingCache {
  [key: string]: number[];  // file path -> embedding
}

// ============================================
// SETTINGS TYPES
// ============================================

export interface PluginSettings {
  // General
  enableOnNoteCreation: boolean;
  confidenceThreshold: number;  // 50-95%
  showDetailedRationale: boolean;

  // OpenAI
  openaiApiKey: string;
  openaiModel: 'gpt-4-turbo' | 'gpt-4' | 'gpt-3.5-turbo';
  temperature: number;
  maxTokens: number;

  // Smart Connections
  useSmartConnectionsIfAvailable: boolean;
  fallbackToOpenAIEmbeddings: boolean;

  // Folder Note Detection
  indexFileNames: string[];  // 'index.md', '_index.md', etc.
  autoCreateFolderNotes: boolean;

  // Content Analysis
  includeFullContent: boolean;
  contentPreviewLength: number;
  analyzeTagsHierarchically: boolean;
  extractHeadings: boolean;

  // Exclusions
  excludedFolders: string[];  // regex patterns
  excludedNotes: string[];    // regex patterns
  excludedTags: string[];

  // Automation
  batchClassificationEnabled: boolean;
  autoMoveIfConfident: boolean;
  autoMoveThreshold: number;

  // UI/UX
  theme: 'auto' | 'light' | 'dark';
  showToolbarButton: boolean;
  defaultAction: 'preview' | 'move' | 'ask';
}

export const DEFAULT_SETTINGS: PluginSettings = {
  enableOnNoteCreation: false,
  confidenceThreshold: 75,
  showDetailedRationale: true,

  openaiApiKey: '',
  openaiModel: 'gpt-4-turbo',
  temperature: 0.3,
  maxTokens: 1000,

  useSmartConnectionsIfAvailable: true,
  fallbackToOpenAIEmbeddings: true,

  indexFileNames: ['index.md', '_index.md', 'README.md'],
  autoCreateFolderNotes: false,

  includeFullContent: false,
  contentPreviewLength: 500,
  analyzeTagsHierarchically: true,
  extractHeadings: true,

  excludedFolders: ['.obsidian', 'Templates', 'Archive'],
  excludedNotes: ['Daily Note.*'],
  excludedTags: ['#archived', '#template'],

  batchClassificationEnabled: false,
  autoMoveIfConfident: false,
  autoMoveThreshold: 90,

  theme: 'auto',
  showToolbarButton: true,
  defaultAction: 'preview',
};
